kind: Service
apiVersion: v1
metadata:
  name: hogwart-express-service
spec:
  type: NodePort
  selector:
    app: hogwart-express
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogwart-express-deployment
  labels:
    app: hogwart-express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hogwart-express
      track: stable
  template:
    metadata:
      labels:
        app: hogwart-express
        track: stable
    spec:
      containers:
      - name: hogwart-express
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m