kind: Service
apiVersion: v1
metadata:
  name: hogwarts-express-service
spec:
  type: NodePort
  selector:
    app: hogwarts-express
  ports:
  - protocol: TCP
    port: 30000
    nodePort: 30000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hogwarts-express-deployment
  labels:
    app: hogwarts-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hogwarts-express
      track: stable
  template:
    metadata:
      labels:
        app: hogwarts-express
        track: stable
    spec:
      containers:
      - name: hogwarts-express
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 30000
        livenessProbe:
          httpGet:
            path: /
            port: 30000
          initialDelaySeconds: 15
          timeoutSeconds: 1
          periodSeconds: 10
        resources:
          requests:
            cpu: 200m
